services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: production
        env_file:
            - .env
        ports:
            - "8001:8000"
networks:
  default:
    name: detector_network
