"""add confidence field

Revision ID: 54a2890737e0
Revises: 20e2a10d5169
Create Date: 2025-09-09 03:56:33.944985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54a2890737e0'
down_revision: Union[str, None] = '20e2a10d5169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('count_analysis_config', sa.Column('confidence', sa.Float(), nullable=False))
    op.create_unique_constraint(None, 'count_analysis_config', ['uuid'])
    op.create_unique_constraint(None, 'frame_mask', ['uuid'])
    op.create_unique_constraint(None, 'object', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    raise NotImplementedError("Downgrades are not allowed")
