"""initial DB structure

Revision ID: ddf11112cb7d
Revises: 
Create Date: 2025-09-27 11:52:17.194503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddf11112cb7d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('count_analysis_config',
    sa.Column('user_uuid', sa.Uuid(), nullable=False),
    sa.Column('resolution_width', sa.Integer(), nullable=False),
    sa.Column('resolution_height', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('jwt_token',
    sa.Column('user_uuid', sa.Uuid(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('user',
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('api_key',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('frame_mask',
    sa.Column('pixel_width', sa.Integer(), nullable=False),
    sa.Column('pixel_height', sa.Integer(), nullable=False),
    sa.Column('count_analysis_config_uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['count_analysis_config_uuid'], ['count_analysis_config.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('object',
    sa.Column('value', sa.Enum('VEHICLE', 'CAR', 'MOTORBIKE', 'BICYCLE', 'BUS', 'TRUCK', name='objectenum'), nullable=False),
    sa.Column('count_analysis_config_uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['count_analysis_config_uuid'], ['count_analysis_config.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    raise NotImplementedError("Downgrades are not allowed")
