"""add example image ID field

Revision ID: 9d1f6e1ed7fa
Revises: 5360333c8e83
Create Date: 2025-11-05 04:40:27.348796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d1f6e1ed7fa'
down_revision: Union[str, None] = '5360333c8e83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object_analysis_config', sa.Column('example_image_uuid', sa.Uuid(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    raise NotImplementedError("Downgrades are not allowed")
