"""add name field for config entries

Revision ID: 2389a7a03b9b
Revises: 9d1f6e1ed7fa
Create Date: 2025-11-09 09:22:38.963467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2389a7a03b9b'
down_revision: Union[str, None] = '9d1f6e1ed7fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object_analysis_config', sa.Column('config_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    raise NotImplementedError("Downgrades are not allowed")
