"""add hashed key column

Revision ID: a3a2b6208c7b
Revises: ddf11112cb7d
Create Date: 2025-09-27 12:46:22.258759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3a2b6208c7b'
down_revision: Union[str, None] = 'ddf11112cb7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_key', sa.Column('hashed_key', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'api_key', ['uuid'])
    op.create_unique_constraint(None, 'count_analysis_config', ['uuid'])
    op.create_unique_constraint(None, 'frame_mask', ['uuid'])
    op.create_unique_constraint(None, 'jwt_token', ['uuid'])
    op.create_unique_constraint(None, 'object', ['uuid'])
    op.create_unique_constraint(None, 'user', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    raise NotImplementedError("Downgrades are not allowed")
