"""add data format for file

Revision ID: 5360333c8e83
Revises: dfdf1bd1b408
Create Date: 2025-11-04 05:54:48.353294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5360333c8e83'
down_revision: Union[str, None] = 'dfdf1bd1b408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('format', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'file', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    raise NotImplementedError("Downgrades are not allowed")
