"""add API key scope

Revision ID: 0abdfb68e1ef
Revises: 454c6b16dae5
Create Date: 2025-10-29 04:34:10.688380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0abdfb68e1ef'
down_revision: Union[str, None] = '454c6b16dae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'account', ['uuid'])
    op.add_column('api_key', sa.Column('scopes', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'api_key', ['uuid'])
    op.create_unique_constraint(None, 'frame_mask', ['uuid'])
    op.create_unique_constraint(None, 'jwt_token', ['uuid'])
    op.create_unique_constraint(None, 'object', ['uuid'])
    op.create_unique_constraint(None, 'object_analysis_config', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    raise NotImplementedError("Downgrades are not allowed")
